import { defineEventHandler, readBody } from 'h3'
import nodemailer from 'nodemailer'

/**
 * Server route to handle sending a full inventory status report.
 */
export default defineEventHandler(async (event) => {
  const config = useRuntimeConfig()
  try {
    const body = await readBody(event)
    const { recipients, items, senderEmail } = body

    if (!recipients || !items) {
      return { success: false, error: 'Missing recipients or data' }
    }

    // 1. Authenticate with Gmail
    const user = config.gmailUser
    const pass = config.gmailAppPassword

    if (!user || !pass) {
      console.error('[Report Email] GMAIL configuration missing')
      return { success: false, error: 'Email service config missing' }
    }

    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: { user, pass }
    })

    // 2. Build the Items Table HTML
    const itemsHtml = items.map((item: any) => `
      <tr style="border-bottom: 1px solid #f1f5f9;">
        <td style="padding: 12px 8px; font-size: 13px; font-weight: bold; color: #1e293b; text-transform: uppercase;">${item.name}</td>
        <td style="padding: 12px 8px; font-size: 13px; text-align: center; font-weight: 900; color: #ea580c;">${item.unopened_count}</td>
        <td style="padding: 12px 8px; font-size: 11px; color: #64748b;">${item.opened_state_notes || '-'}</td>
        <td style="padding: 12px 8px; font-size: 11px; text-align: right; color: ${new Date(item.nearest_expiry_date) < new Date() ? '#ef4444' : '#64748b'}">${item.nearest_expiry_date || 'N/A'}</td>
      </tr>
    `).join('')

    const dateStr = new Date().toLocaleDateString('en-MY', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })

    // 3. Send the Email
    await transporter.sendMail({
      from: `"Drip & Brew Inventory" <${user}>`,
      to: recipients,
      subject: `📊 Full Inventory Status Report - ${dateStr}`,
      priority: 'high',
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 40px 20px; color: #1e293b;">
          <h1 style="font-size: 24px; font-weight: 900; text-transform: uppercase; italic; letter-spacing: -0.02em; color: #000000; margin-bottom: 8px;">
            Inventory Status Report
          </h1>
          <p style="font-size: 11px; font-weight: 900; text-transform: uppercase; letter-spacing: 0.2em; color: #ea580c; margin-bottom: 30px;">
            Generated by ${senderEmail} • ${dateStr}
          </p>
          
          <table style="width: 100%; border-collapse: collapse; background-color: #ffffff;">
            <thead>
              <tr style="background-color: #f8fafc; border-bottom: 2px solid #e2e8f0;">
                <th style="padding: 12px 8px; text-align: left; font-size: 10px; font-weight: 900; text-transform: uppercase; color: #94a3b8;">Item</th>
                <th style="padding: 12px 8px; text-align: center; font-size: 10px; font-weight: 900; text-transform: uppercase; color: #94a3b8;">Qty</th>
                <th style="padding: 12px 8px; text-align: left; font-size: 10px; font-weight: 900; text-transform: uppercase; color: #94a3b8;">Notes</th>
                <th style="padding: 12px 8px; text-align: right; font-size: 10px; font-weight: 900; text-transform: uppercase; color: #94a3b8;">Expiry</th>
              </tr>
            </thead>
            <tbody>
              ${itemsHtml}
            </tbody>
          </table>

          <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #f1f5f9; text-align: center;">
            <p style="font-size: 10px; font-weight: 800; color: #cbd5e1; text-transform: uppercase; letter-spacing: 0.1em;">
              Drip & Brew POS • Harvest Generation
            </p>
          </div>
        </div>
      `
    })

    console.log('[Report Email] Success: Report sent to', recipients)
    return { success: true }

  } catch (err: any) {
    console.error('[Report Email] Global Error:', err.message)
    return { success: false, error: err.message }
  }
})
