import { defineEventHandler, readBody } from 'h3'
import nodemailer from 'nodemailer'
import { createClient } from '@supabase/supabase-js'
import type { Database } from '~/types/supabase'

/**
 * Server route to handle sending a full inventory status report.
 */
export default defineEventHandler(async (event) => {
  const config = useRuntimeConfig()
  
  try {
    const body = await readBody(event)
    const { recipients, items, senderEmail } = body

    if (!recipients || !items) {
      return { success: false, error: 'Missing recipients or data' }
    }

    // --- 1. Data Fetching ---
    const supabase = createClient<Database>(config.public.supabaseUrl, config.supabaseServiceKey)
    
    // Fetch latest weekly analytics
    const { data: analytics } = await supabase.rpc('get_weekly_analytics').limit(1)
    const stats = analytics?.[0]

    // --- 2. Formatters & Date Info ---
    const currency = new Intl.NumberFormat('en-MY', { style: 'currency', currency: 'MYR' })
    const now = new Date()
    const nowStr = now.toLocaleDateString('en-MY', { 
      day: '2-digit', month: 'short', year: 'numeric', 
      hour: '2-digit', minute: '2-digit', timeZone: 'Asia/Kuala_Lumpur'
    })

    // Prepare exactly the 5 fields requested
    const summary = {
      dateRange: stats ? getWeekRange(stats.date) : 'New Week (No orders)',
      orders: stats?.total_orders_count || 0,
      grossOrder: currency.format(stats?.gross_sales || 0),
      sales: currency.format(stats?.net_sales || 0),
      cupsSold: stats?.total_cups_sold || 0
    }

    // --- 3. Email Send ---
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: { user: config.gmailUser, pass: config.gmailAppPassword }
    })

    const itemsTable = items.map((item: any) => `
      <tr style="border-bottom: 1px solid #f1f5f9;">
        <td style="padding: 12px 8px; font-size: 13px; font-weight: bold; color: #1e293b;">${item.name}</td>
        <td style="padding: 12px 8px; font-size: 13px; text-align: center; font-weight: 900; color: #ea580c;">${item.unopened_count}</td>
        <td style="padding: 12px 8px; font-size: 11px; color: #64748b;">${item.opened_state_notes || '-'}</td>
        <td style="padding: 12px 8px; font-size: 11px; text-align: right; color: ${new Date(item.nearest_expiry_date) < now ? '#ef4444' : '#64748b'}">${item.nearest_expiry_date || 'N/A'}</td>
      </tr>
    `).join('')

    await transporter.sendMail({
      from: `"Drip & Brew Inventory" <${config.gmailUser}>`,
      to: recipients,
      subject: `📊 Full Inventory Status Report - ${nowStr}`,
      priority: 'high',
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 40px 20px; color: #1e293b;">
          <h1 style="font-size: 24px; font-weight: 900; italic; color: #000000; margin-bottom: 8px; text-transform: uppercase;">Inventory Report</h1>
          <p style="font-size: 11px; font-weight: 900; color: #ea580c; margin-bottom: 30px; letter-spacing: 0.1em; text-transform: uppercase;">
            Generated by ${senderEmail} • ${nowStr}
          </p>

          <div style="margin-bottom: 40px; padding: 25px; background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 20px;">
            <p style="margin: 0 0 15px 0; font-size: 10px; font-weight: 900; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.1em;">Weekly Summary</p>
            <table style="width: 100%; border-collapse: collapse;">
              ${row('Week Range', summary.dateRange)}
              ${row('Orders', summary.orders)}
              ${row('Gross Orders', summary.grossOrder)}
              ${row('Sales', summary.sales, true)}
              ${row('Cups Sold', summary.cupsSold)}
            </table>
          </div>
          
          <table style="width: 100%; border-collapse: collapse;">
            <thead>
              <tr style="background-color: #f8fafc; border-bottom: 2px solid #e2e8f0; text-transform: uppercase;">
                <th style="padding: 12px 8px; text-align: left; font-size: 10px; font-weight: 900; color: #94a3b8;">Item</th>
                <th style="padding: 12px 8px; text-align: center; font-size: 10px; font-weight: 900; color: #94a3b8;">Qty</th>
                <th style="padding: 12px 8px; text-align: left; font-size: 10px; font-weight: 900; color: #94a3b8;">Notes</th>
                <th style="padding: 12px 8px; text-align: right; font-size: 10px; font-weight: 900; color: #94a3b8;">Expiry</th>
              </tr>
            </thead>
            <tbody>${itemsTable}</tbody>
          </table>
        </div>
      `
    })

    return { success: true }
  } catch (err: any) {
    console.error('[Report Email] Error:', err.message)
    return { success: false, error: err.message }
  }
})

// --- Helpers ---
function getWeekRange(dateStr: string) {
  const start = new Date(dateStr)
  const end = new Date(start)
  end.setDate(start.getDate() + 6)
  const f = (d: Date) => d.toLocaleDateString('en-MY', { month: 'short', day: 'numeric', timeZone: 'Asia/Kuala_Lumpur' })
  return `${f(start)} - ${f(end)}`
}

function row(label: string, value: string | number, high = false) {
  return `
    <tr>
      <td style="padding: 10px 0; border-bottom: 1px solid #e2e8f0; font-size: 11px; color: #64748b; font-weight: 700; text-transform: uppercase;">${label}</td>
      <td style="padding: 10px 0; border-bottom: 1px solid #e2e8f0; text-align: right; font-size: 13px; font-weight: 900; color: ${high ? '#ea580c' : '#1e293b'};">${value}</td>
    </tr>
  `
}
